### ISSUE TITLE
'connect to rhino' failure

### ISSUE THREAD

**Issue by Simcha-git** [savanna-projects/rhino-vscode-extension#20]
When trying to open the tests from the folder above the manifest, the connect to rhino fails

![image](https://user-images.githubusercontent.com/76996673/180976350-3297a8fa-5b78-49a8-a2cd-efb6b20d647e.png)
success

![image](https://user-images.githubusercontent.com/76996673/180977116-6ab8ff3b-604c-41e2-a3c9-786a26d73675.png)
failure - loading without stop

**Comment by gravity-api** [comment]
not an issue - connected from the wrong root folder
