### ISSUE TITLE
VSCode - Action Auto Complete without argument isn't valid for some actions 

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-vscode-extension#5]
Some actions like "go to url" shows without argument although the action required an argument to run, 
while for some like, "refresh" that isn't require an argument - this is ok

Can we change the auto complete to show only the valid action arguments via auto compete?

**Comment by gravity-api** [comment]
Not a bug, this is the current behavior.
The language is pulled from Rhino Metadata
