### ISSUE TITLE
VSCode - Rhino report doesn't present special characters and the word in between in the TC title like: "<abc>"

### ISSUE THREAD

**Issue by YanivAroch** [savanna-projects/rhino-vscode-extension#6]
![image](https://user-images.githubusercontent.com/70174048/117051766-962c2900-ad1f-11eb-811b-f9fb4b2bca14.png)

![image](https://user-images.githubusercontent.com/70174048/117051715-86ace000-ad1f-11eb-8f00-6b1b53f13f0a.png)

**Comment by gravity-api** [comment]
Resolved - open/close tags removed from the snippet.
